export const MUNICH_DISTRICTS = [
  { slug: "altstadt-lehel", label: "Altstadt-Lehel" },
  { slug: "maxvorstadt", label: "Maxvorstadt" },
  { slug: "schwabing-west", label: "Schwabing-West" },
  { slug: "schwabing-freimann", label: "Schwabing-Freimann" },
  { slug: "bogenhausen", label: "Bogenhausen" },
  { slug: "au-haidhausen", label: "Au-Haidhausen" },
  { slug: "sendling", label: "Sendling" },
  { slug: "sendling-westpark", label: "Sendling-Westpark" },
  { slug: "schwanthalerhoehe", label: "Schwanthalerhöhe" },
  { slug: "neuhausen-nymphenburg", label: "Neuhausen-Nymphenburg" },
  { slug: "moosach", label: "Moosach" },
  { slug: "milbertshofen", label: "Milbertshofen-Am Hart" },
  { slug: "berg-am-laim", label: "Berg am Laim" },
  { slug: "trudering-riem", label: "Trudering-Riem" },
  { slug: "ramersdorf-perlach", label: "Ramersdorf-Perlach" },
  { slug: "obergiesing", label: "Obergiesing-Fasangarten" },
  { slug: "untergiesing", label: "Untergiesing-Harlaching" },
  { slug: "thalkirchen", label: "Thalkirchen-Obersendling" },
  { slug: "hadern", label: "Hadern" },
  { slug: "pasing-obermenzing", label: "Pasing-Obermenzing" },
  { slug: "aubing-lochhausen", label: "Aubing-Lochhausen-Langwied" },
  { slug: "allach-untermenzing", label: "Allach-Untermenzing" },
  { slug: "feldmoching-hasenbergl", label: "Feldmoching-Hasenbergl" },
  { slug: "laim", label: "Laim" },
  { slug: "ludwigsvorstadt-isarvorstadt", label: "Ludwigsvorstadt-Isarvorstadt" },
  // Umkreis München
  { slug: "gruenwald", label: "Grünwald" },
  { slug: "pullach", label: "Pullach im Isartal" },
  { slug: "deisenhofen", label: "Deisenhofen" },
  { slug: "ottobrunn", label: "Ottobrunn" },
  { slug: "neubiberg", label: "Neubiberg" },
  { slug: "unterhaching", label: "Unterhaching" },
  { slug: "taufkirchen", label: "Taufkirchen" },
  { slug: "oberhaching", label: "Oberhaching" },
  { slug: "haar", label: "Haar" },
  { slug: "vaterstetten", label: "Vaterstetten" },
  { slug: "poing", label: "Poing" },
  { slug: "kirchheim", label: "Kirchheim bei München" },
  { slug: "feldkirchen", label: "Feldkirchen" },
  { slug: "aschheim", label: "Aschheim" },
  { slug: "ismaning", label: "Ismaning" },
  { slug: "garching", label: "Garching bei München" },
  { slug: "unterschleissheim", label: "Unterschleißheim" },
  { slug: "oberschleissheim", label: "Oberschleißheim" },
  { slug: "dachau", label: "Dachau" },
  { slug: "karlsfeld", label: "Karlsfeld" },
  { slug: "germering", label: "Germering" },
  { slug: "planegg", label: "Planegg" },
  { slug: "krailling", label: "Krailling" },
  { slug: "gauting", label: "Gauting" },
  { slug: "starnberg", label: "Starnberg" },
  { slug: "gruenbwald-isartal", label: "Grünwald / Isartal" },
  { slug: "egling", label: "Egling an der Paar" },
  { slug: "hohenbrunn", label: "Hohenbrunn" },
  { slug: "brunnthal", label: "Brunnthal" },
  { slug: "sauerlach", label: "Sauerlach" },
  { slug: "wolfratshausen", label: "Wolfratshausen" },
  { slug: "geretsried", label: "Geretsried" },
] as const
